/*
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Project     : R3ISC-V
 * File        : InstrMem.sv
 * Author      : JoeK
 * Created     : 2026/08/08
 *
 * Description : Instruction memory, DEPTH deep
 *
 * License     : None
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

module InstrMem #(parameter int WORD_WIDTH = 32
                , parameter int ADDR_WIDTH = 32 
                , parameter int DEPTH = 256
                )  ( input logic [ADDR_WIDTH - 1 : 0] addr
                   , output logic [WORD_WIDTH - 1 : 0] readData
                   );
                

  logic [WORD_WIDTH - 1 : 0] mem [DEPTH - 1 : 0];

  initial
  begin: PopulateInstrMem // This test program was generated by copilot.
    //$readmemh("instrMem.hex", mem);
    mem[0] = 32'h00500093; // ADDI x1, x0, 5
    mem[1] = 32'h00A00113; // ADDI x2, x0, 10
    mem[2] = 32'h002081B3; // ADD  x3, x1, x2
    mem[3] = 32'h0030A223; // SW   x3, 0(x1)
    mem[4] = 32'h0000A283; // LW   x5, 0(x1)
    mem[5] = 32'h0051A333; // AND  x6, x3, x5
    mem[6] = 32'h0051A3B3; // OR   x7, x3, x5
    mem[7] = 32'h00528463; // BEQ  x5, x5, +8
    mem[8] = 32'h00000013; // NOP (ADDI x0,x0,0)
    mem[9] = 32'h00000013;
    mem[10] = 32'h00000013;
    mem[11] = 32'h00000013;
    mem[12] = 32'h00000013;
    mem[13] = 32'h00000013;
    mem[14] = 32'h00000013;
    mem[15] = 32'h00000013;
  end

  assign readData = mem[addr[31 : 2]]; //word alligned

endmodule